//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisSamochodowy.Baza_danych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Konta
    {
        public int Konto_ID { get; set; }
        public string Imie { get; set; }
        public string Nazwisko { get; set; }
        public string Miasto { get; set; }
        public string E_mail { get; set; }
        public string Nr_telefonu { get; set; }
        public string Login { get; set; }
        public string Haslo { get; set; }
    }
}
