//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SerwisSamochodowy.Baza_danych
{
    using System;
    using System.Collections.Generic;
    
    public partial class Samochody
    {
        public System.Guid Samochod_ID { get; set; }
        public int Kategoria_ID { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Kolor { get; set; }
        public string Rok_produkcji { get; set; }
        public double Przebieg { get; set; }
        public string Rodzaj_paliwa { get; set; }
        public string Nr_vin { get; set; }
        public double Cena { get; set; }
        public string Nr_kontaktowy { get; set; }
        public string Opis { get; set; }
        public string Zdjecie { get; set; }
    }
}
